### ISSUE TITLE
Flat field creation failure on normalization

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#100]
I'm having a persistent problem with one of the SXD datasets from 2003 which fails on the flat creation:

relevant dataset: https://drive.google.com/file/d/1TTNXW9FRUaQ5YxD8HmDsjlQ8baoh-mvJ/view?usp=drive_link

code snippet (out of batch)

```
import os
import pyspextool as ps
from pyspextool.batch import batch
from pyspextool import config as setup
from pyspextool.io.files import extract_filestring,make_full_path
from pyspextool.utils.arrays import numberList

folder = '/Users/adam/projects/spex_archive/reductions/20030523-test/'

ps.pyspextool_setup('spex',raw_path=folder+'data/', cal_path=folder+'cals/',proc_path=folder+'proc/', qa_path=folder+'qa/',qa_extension='.pdf',verbose=True)
cs = '136-143'
indexinfo = {'nint': setup.state['nint'], 'prefix': 'flat','suffix': '.a', 'extension': '.fits'}
temp_files = make_full_path(folder+'data/',cs, indexinfo=indexinfo)
input_files = list(filter(lambda x: os.path.exists(x),temp_files))
fnum = [int(os.path.basename(f).replace('flat','').replace('.a.fits','').replace('.b.fits','')) for f in input_files]
fstr = '{}'.format(numberList(fnum))
ps.extract.make_flat(['flat',fstr],'flat{}'.format(cs),qa_plot=False,qa_file=False,verbose=True)
```

response:

Pyspextool Setup
----------------
Instrument:  spex

Rawpath:  /Users/adam/projects/spex_archive/reductions/20030523-test/data
Calpath:  /Users/adam/projects/spex_archive/reductions/20030523-test/cals
Procpath:  /Users/adam/projects/spex_archive/reductions/20030523-test/proc
Qapath:  /Users/adam/projects/spex_archive/reductions/20030523-test/qa

QA Extension: .pdf
QA Plot: False
QA File: True 

Generating Flat Field
---------------------
Loading images...
100% |**********************************************************************|
Scaling images...
Medianing the images...
Locating the orders...
Normalizing the median image...
Normalizing the flat...
 67% |***********************************************                       |
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/jh/fr3p41p17r1g6v0t6k0c2xy00000gq/T/ipykernel_1810/3335154482.py in <module>
     16 fnum = [int(os.path.basename(f).replace('flat','').replace('.a.fits','').replace('.b.fits','')) for f in input_files]
     17 fstr = '{}'.format(numberList(fnum))
---> 18 ps.extract.make_flat(['flat',fstr],'flat{}'.format(cs),qa_plot=False,qa_file=False,verbose=True)

~/python_codes/pyspextool/src/pyspextool/extract/make_flat.py in make_flat(files, output_name, extension, normalize, overwrite, qa_plot, qa_plotsize, qa_file, verbose)
    245             print('Normalizing the median image...')
    246 
--> 247         nimg, nvar, rms = normalize_flat(med, edgecoeffs, modeinfo['xranges'],
    248                                          modeinfo['slith_arc'],
    249                                          modeinfo['nxgrid'],

~/python_codes/pyspextool/src/pyspextool/extract/normalize_flat.py in normalize_flat(img, edgecoeffs, xranges, slith_arc, nxgrid, nygrid, var, oversamp, ybuffer, verbose)
    113         # Do the rectification
    114 
--> 115         order = rectify_order(img, xidx, yidx, ybuffer=ybuffer)
    116 
    117         # Fiterpolate the results after median smoothing to minimize bad pixels

~/python_codes/pyspextool/src/pyspextool/extract/rectify_order.py in rectify_order(img, xidx, yidx, var, bpmask, bsmask, ybuffer)
     57 
     58     f = interpolate.RegularGridInterpolator(points, img)
---> 59     img = f((yidx, xidx))
     60 
     61     ny, nx = img.shape

~/opt/anaconda3/lib/python3.9/site-packages/scipy/interpolate/_rgi.py in __call__(self, xi, method)
    327             raise ValueError("Method '%s' is not defined" % method)
    328 
--> 329         xi, xi_shape, ndim, nans, out_of_bounds = self._prepare_xi(xi)
    330 
    331         if method == "linear":

~/opt/anaconda3/lib/python3.9/site-packages/scipy/interpolate/_rgi.py in _prepare_xi(self, xi)
    381                 if not np.logical_and(np.all(self.grid[i][0] <= p),
    382                                       np.all(p <= self.grid[i][-1])):
--> 383                     raise ValueError("One of the requested xi is out of bounds "
    384                                      "in dimension %d" % i)
    385             out_of_bounds = None

ValueError: One of the requested xi is out of bounds in dimension 0

I've included the locate_orders.pdf plot which looks fine, just seems to be a normalization issue?

[flat136-143_locateorders.pdf](https://github.com/pyspextool/pyspextool/files/12186527/flat136-143_locateorders.pdf)

**Comment by michaelcushing** [comment]
Fixed.  Didn't associate this issue number with the push though.
