### ISSUE TITLE
Expand `check_parameter` with type hinting

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#102]
Many functions make extensive use the `check_parameter` function which makes sure the input parameter is the type expected.  This could be expanded on by using this same info to add type hints to those same functions. 

We could also then use `mypy` to help find bugs.

Here are some relevant links:
- https://docs.python.org/3/library/typing.html
- https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html
- https://towardsdatascience.com/12-beginner-concepts-about-type-hints-to-improve-your-python-code-90f1ba0ac49

**Comment by kelle** [comment]
This feature is implemented differently in Python 3.9 vs 3.10 and this motivates me to drop support for 3.9.  I'll open a new issue...

**Comment by michaelcushing** [comment]
There is a package called typing that allows you to do useful things:

https://docs.python.org/3/library/typing.html

For example, I often use None as a marker of "go use the default in setup but if you give me something, I will override it".  To type hint that you can using qa_write:typing.Optional[bool]=None.

**Comment by michaelcushing** [comment]
Also, ndarray doesn't work. Must use another package in numpy.

https://numpy.org/doc/stable/reference/typing.html#module-numpy.typing

**Comment by michaelcushing** [comment]
I am adding type hinting to all new code, and have been adding it as I go back through old code.
