### ISSUE TITLE
Drop support for Python 3.9

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#104]
Right now, we're running tests for Python 3.9, 3.10, and 3.11.  We recommend (via the envirnoment.yml file) Python 3.11.

I'd like to start implementing type hinting (#102 ) which is handled differently in Python 3.9 than it is in 3.10 and 11.

Since Python 3.9 is no longer receiving updates and we aren't using any legacy code, I motion that we drop support for Python 3.9.  ([Status of Python Versions](https://devguide.python.org/versions/).)

In practice, this means I'm just going to stop running the tests with Python 3.9.

**Comment by aburgasser** [comment]
ok with me
