### ISSUE TITLE
extraction warning resulting in missing data, occasional failure

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#107]
Getting a persistent "divide by zero" warning that sometimes stops the extraction and sometimes doesn't

Optimally extracting 2 apertures in 1 orders (with background subtraction)...
/Users/adam/python_codes/pyspextool/src/pyspextool/extract/extract_pointsource_1dxd.py:421: RuntimeWarning: divide by zero encountered in divide
  np.abs(slit_psf/np.nansum(slit_psf[z_psf]))
/Users/adam/python_codes/pyspextool/src/pyspextool/extract/extract_pointsource_1dxd.py:421: RuntimeWarning: invalid value encountered in divide
  np.abs(slit_psf/np.nansum(slit_psf[z_psf]))

when the code doesn't halt, the spectra have sections that are missing; other times the code crashes on plotting:

Wrote spectra0085.fits to disk.
Traceback (most recent call last):
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 227, in <module>
    app = runBatch()
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 197, in __init__
    batch.batch_reduce(par,verbose=(not args['quiet']))
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/batch/batch.py", line 1392, in batch_reduce
    ps.extract.do_all_steps([spar['TARGET_PREFIX'],'{}'.format(numberList(fnum))],verbose=spar['VERBOSE'])
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/extract/do_all_steps.py", line 193, in do_all_steps
    extract_apertures(verbose=extract.extract['verbose'])
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/extract/extract_apertures.py", line 235, in extract_apertures
    write_apertures(spectra, psbginfo=psbginfo, xsbginfo=xsbginfo,
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/extract/extract_apertures.py", line 508, in write_apertures
    plot_spectra(output_fullpath + '.fits',flag_linearity=True,
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/plot/plot_spectra.py", line 214, in plot_spectra
    fig = plot_aperture(sub_spectra, i, ytype, colors, line_width,
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/plot/plot_spectra.py", line 295, in plot_aperture
    wranges, yranges = get_ranges(spectra, ytype, fraction=yrange_buffer)
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/plot/plot_spectra.py", line 470, in get_ranges
    sg_array = robust_savgol(x_values, array, 11)['fit']
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/fit/robust_savgol.py", line 80, in robust_savgol
    newyy = scipy.signal.savgol_filter(yy, window_length, polyorder)
  File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/scipy/signal/_savitzky_golay.py", line 345, in savgol_filter
    raise ValueError("If mode is 'interp', window_length must be less "
ValueError: If mode is 'interp', window_length must be less than or equal to the size of x.

looks like there might be an uncorrected nan somewhere (because of bad pixel mask?) that is causing a whole slew of nan errors.

dataset where this occured: https://drive.google.com/file/d/1dG-pmAZ0Wwqr8jaZY9GN5WW2eQxh1S8F/view?usp=sharing

**Comment by michaelcushing** [comment]
Can you tell me the aperture parameters you used for this?  I cannot reproduce this problem as I get through the entire series 66-88. 

One thing that I did notice was that the first two spectra are "bad" in the sense that I suspect there was a standard star observed before this series so the pair subtraction isn't the standard looking one.

[ast0065.a_ast0066.b_image.pdf](https://github.com/pyspextool/pyspextool/files/12303790/ast0065.a_ast0066.b_image.pdf)

**Comment by aburgasser** [comment]
OBSERVATION_PARAMETERS_OPTIONAL = {
	'ORDERS': '3-9',
	'REDUCTION_MODE': 'A-B',
	'NPOSITIONS': 2,
	'APERTURE_POSITIONS': [3.7,11.2],
	'APERTURE_METHOD': 'auto',
	'APERTURE': 1.5,
	'PSF_RADIUS': 1.5,
	'BACKGROUND_RADIUS': 2.5,
	'BACKGROUND_WIDTH': 4,
	'SCALE_RANGE': [1.0,1.5],

**Comment by michaelcushing** [comment]
So I ran with these parameters and it also worked.  @ctheissen could you download these data and give it a try with the latest code (I forked from main before I started working on these).

**Comment by ctheissen** [comment]
I was able to get it to run after I modified the notebook example a bit (we really need to update that). One thing in the params @aburgasser has listed above, the orders for prism had to be set to '1' (at least for me) or it would throw an error since only SXD has 3-9.

That being said, I get the exact same error as @aburgasser if I run with src_files = '65-88'
However, if I use src_files = '67-88', bypassing the bad files @michaelcushing mentioned, then it runs perfectly.
<img width="895" alt="Screenshot 2023-08-10 at 2 18 06 PM" src="https://github.com/pyspextool/pyspextool/assets/7979844/5b5de2ce-cf50-4e30-86ed-f308124d87a8">

**Comment by michaelcushing** [comment]
Jesus.  How am I able to run it!  Maybe I am just magic.  Maybe I have something in mine that you all don't.  let me finish what I am working on and do a pull request and then we can re-visit this.

**Comment by ctheissen** [comment]
I suspect part of the issue, which occurs at the `ps.extract.do_all_steps`, is the fact that spectra0065.fits is never created. Here is some of the output where that file is bypassed and spectra0066.fits is made twice.

Loading the flat...
Loading the wavecal...
Loading ast0065.a.fits, ast0066.b.fits and correcting for non-linearity...
Loading images...
100% |**********************************************************************|
Flat fielding the image...
Setting extraction type to point source...
Creating the spatial profiles...
Locating the apertures...
Aperture signs are (-, -)...
Updating order selection...
/Users/ctheissen/miniconda3/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
Tracing apertures...
100% |**********************************************************************|
Collecting plotting data for trace...
100% |**********************************************************************|
Optimally extracting 2 apertures in 1 orders (with background subtraction)...
100% |**********************************************************************|
Wrote spectra0066.fits to disk.
 
Loading ast0065.a.fits, ast0066.b.fits and correcting for non-linearity...
Loading images...
100% |**********************************************************************|
Flat fielding the image...
Previous steps not completed.
Locating the apertures...
Aperture signs are (-, -)...
Updating order selection...
/Users/ctheissen/miniconda3/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
Tracing apertures...
100% |**********************************************************************|
Collecting plotting data for trace...
100% |**********************************************************************|
Optimally extracting 2 apertures in 1 orders (with background subtraction)...
100% |**********************************************************************|
Wrote spectra0066.fits to disk.

**Comment by michaelcushing** [comment]
I have reproduced the problem.  Will focus on this now.
