### ISSUE TITLE
Use of the home directory?

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#110]
I'm finally to the point where I'm trying to run things and I've just noticed that `pyspextool_setup` adds a file to the users home directory (`.pyspextool_spex.dat`). This makes me very uncomfortable for many reasons.  

Could someone explain to me the purpose of the files in the users home directory?

**Comment by michaelcushing** [comment]
It goes back to the IDL version.  The idea is to not have the user have to add the paths in each and every time they start the GUI up.  In principle if people are using the python version in batch or script mode this isn't necessary, but if they are using it at the command line, it might get annoying (although arrow up could be used).  

I am not wedded to keeping this feature.  However, we have talked about writing out a log after each step and that is going to have to get written somewhere.  Could be in the proc/ directory which eliminates things going into the home directory.

**Comment by kelle** [comment]
Writing the directories was "disabled" via commenting in #112.  We can decide later if we want to bring this functionality back.
