### ISSUE TITLE
clone of test data did not work

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#113]
I've updated the code and tried the command 

git submodule update --init --recursive

but that didn't work for permission reasons?

% git submodule update --init --recursive

Submodule 'tests/test_data' (git@github.com:pyspextool/test_data.git) registered for path 'tests/test_data'
Cloning into '/Users/adam/python_codes/pyspextool/tests/test_data'...
The authenticity of host 'github.com (192.30.255.113)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pyspextool/test_data.git' into submodule path '/Users/adam/python_codes/pyspextool/tests/test_data' failed
Failed to clone 'tests/test_data'. Retry scheduled
Cloning into '/Users/adam/python_codes/pyspextool/tests/test_data'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pyspextool/test_data.git' into submodule path '/Users/adam/python_codes/pyspextool/tests/test_data' failed
Failed to clone 'tests/test_data' a second time, aborting

**Comment by kelle** [comment]
When you do github stuff, does it prompt you for your password?  Have you [setup an SSH Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for the machine you're trying to use?

**Comment by aburgasser** [comment]
I have set up a key, but may have been on previous machine. if this is a requirement it needs to be clearly detailed (no hidden instructions!)

**Comment by aburgasser** [comment]
yup, that was it, I have a public key but just needed to add it to my github account, so let's be sure to add this caveat/instruction to the DEVELOPER instructions (probably not needed for general usage)
