### ISSUE TITLE
[DISCUSSION] Proposed API change to `pyspextool_setup`

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#120]
Currently, the call to `pyspextool_setup` is quite long:

**1. Explicit:**
```python
raw_path = tdfolder
cal_path = redux_folder+'/cals/'
proc_path = redux_folder+'/proc/'
qa_path = redux_folder+'/cals/'

pyspextool_setup(instrument,raw_path=raw_path, cal_path=cal_path, proc_path=proc_path, 
                    qa_path=qa_path,verbose=True)
```
I propose consolidating the input by passing a dictionary of paths instead of individual strings.

**2. Consolidated:**
```python
spex_prism_paths = {
    'raw_path':  'tests/test_data/spex-prism/data/',
    'cal_path':  'tests/test_data/spex-prism/cals/',
    'proc_path': 'tests/test_data/spex-prism/proc/',
    'qa_path': 'tests/test_data/spex-prism/qa/',
    }

pyspextool_setup(instrument, paths=spex_prism_paths, 
                    qa_path=qa_path, verbose=True)
```   

Either way, under the hood, I'm going to change the paths into a dictionary (or `TypedDict`), but this is a question about the user interface. Which call to `pyspextool_setup` do you think is better for our users?

**Comment by michaelcushing** [comment]
Kelle and I have talked about this a bit and my opinion was that it was better to have each value separate because it is easier for the user.   I personally like to see all the things I have to potentially pass without having to see a single thing and then go down to the doc strong to figure out what goes in that thing.

**Comment by aburgasser** [comment]
I prefer keeping as is. Right now the demonstration notebooks have the specifying these variables line by line, which makes more sense for the lay user, and it makes the docstring cleaner (lists every variable). If the user wants a more compact form and are pythongenic they can always specify as 

```
spex_prism_paths = {
    'raw_path':  'tests/test_data/spex-prism/data/',
    'cal_path':  'tests/test_data/spex-prism/cals/',
    'proc_path': 'tests/test_data/spex-prism/proc/',
    'qa_path': 'tests/test_data/spex-prism/qa/',
    }

pyspextool_setup(instrument, **spex_prism_paths, verbose=True)
```

**Comment by aburgasser** [comment]
consensus is majority apathy with passionate outliers. we'll keep as is
