### ISSUE TITLE
Trace Optimize Warning

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#134]
Figure out how to suppress the following warning:

/opt/homebrew/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',

during tracing.  It is not a "problem" and therefore doesn't need to come up all the time.

**Comment by kelle** [comment]
https://stackoverflow.com/questions/66157609/how-to-hide-delta-grad-0-0-warning-in-scipy-optimize-minimize

**Comment by michaelcushing** [comment]
Figured it out.  Part of Issue #107 fix (but forgot to mention it in the commit).
