### ISSUE TITLE
Using latest SciPy?

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#140]
Got this error on a pytest.  Unclear whether we/I aren't using the latest version of SciPy or whether the latest version needs to be updated which is out of our hands.

  /opt/homebrew/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1069: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    else dtype(mean))

**Comment by kelle** [comment]
Since we are not pinning any of our packages, we are "using" the latest version. This error happened on your local machine and I suspect would resolve if you updated your local scipy.
