### ISSUE TITLE
Challenge with not enough 0s in raw files

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#147]
While messing around with the the new test-data folder, I ran into an issue where `combine_spectra` wouldn't find spectra0001 because it was looking for spectra00001.  
`ps.combine.combine_spectra(["spectra", "1-7"], "spectra1-7", statistic="mean")`

I tried to track down in the code where it does this indexing but I couldn't find it.  I just added the extra 0s to the filenames, but I think this might be a bug somewhere.

**Comment by michaelcushing** [comment]
Not a bug.  The difference between the upgraded SpeX and the older SpeX.  I suspect your setup was set for uSpeX but you were trying to combine data from the old SpeX.  The instrument gets changed in the setup call.

**Comment by kelle** [comment]
Could you please be more explicit. How do I change the setup call so I can use the original filenames.  Here's the relevant test:
https://github.com/kelle/pyspextool/blob/test-data-reorg/tests/test_combine.py

**Comment by michaelcushing** [comment]
you can add instrument='SpeX' to your pyspextool_setup call.

**Comment by kelle** [comment]
turns out 'SpeX' broke things! It must be 'spex'.  I added some code to catch this.
