### ISSUE TITLE
`telluric_correction` always using Vega5000

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#150]
There is code in `telluric_correction` which looks like it should sometimes use Vega5000 and other times use Vega50000 but [it's hard coded to use Vega5000 all the time](https://github.com/pyspextool/pyspextool/blob/95c8929f4a9e0280c421b947619a1f8c79d4b693/src/pyspextool/telluric/telluric_correction.py#L307). Not sure if this on purpose or not but I'm opening this issue just in case it's a real bug.

In #149 , I commented out the un-used code to emphasize that it's always using Vega5000.

**Comment by michaelcushing** [comment]
This was fixed in my last big push.
