### ISSUE TITLE
dust_extinction package required

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#154]
The astropy-related package dust_extinction is now required to run pySpextool.  Where does this have to go in instructions/lists?

**Comment by kelle** [comment]
Need to update `environment.yml` and `pyproject.toml.`

Also, in `pyproject.toml` we say >=3.9 but we're only testing 3.10 and 3.11.  I think we should say >=3.10.

and should we alse specify python version to environment.yml?

**Comment by kelle** [comment]
We've already decided to drop 3.9 but we need to specify 3.11 in the environment.yml: https://github.com/pyspextool/pyspextool/issues/104

**Comment by kelle** [comment]
Maybe only 3.10 in enviroment.yml!  https://docs.conda.io/projects/conda/en/23.1.x/user-guide/tasks/manage-python.html#:~:text=Anaconda%20supports%20Python%203.7%2C%203.8,current%20default%20is%20Python%203.9.

**Comment by kelle** [comment]
Done in #148

**Comment by aburgasser** [comment]
I believe this is now resolved
