### ISSUE TITLE
Screen Size

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#165]
I would like to be able to control the size of figures displayed on the screen by knowing the screen size.  However from everything I read, there is no simple way to do this - it is a function of the OS, the backend, and apparently what day of the week it is.  However, if we limit our code to certain backends, etc. then perhaps I could do it.  So the question is, is that a reasonable thing to do?  I feel like that is just one more problem for the user that we want to try and avoid.  Or it is common for packages to limit backends?

**Comment by kelle** [comment]
Could you say more...give an example? I assume this would be relevant to  `matplotlib` functions?

**Comment by michaelcushing** [comment]
So for example, laptop screens require smaller figures than monitor screens.  I would like to be able to figure out how big the screen is in pixels/DPI, so that I can create a figure that is an appropriate size.  

It might be that we move on to a different plotting package in the future in which case this is moot.

**Comment by kelle** [comment]
Right now, what command would you modify. Is it the calls to matplotlib?

**Comment by michaelcushing** [comment]
Yeah.  Currently I am just setting the size to something "reasonable" using figsize  when I start the plot.  So if I could figure out the screen size, I could then determine what reasonable is in each case (say 50% of the screen) and then pass that to figsize.

**Comment by kelle** [comment]
After a bit of googling, I think this is gonna be hard and honestly, shouldn't be a high priority. 

If anything, provide size arguments in the functions which make plots so the user can decide for themselves if they don't like the defaults you've chosen.

**Comment by michaelcushing** [comment]
Ok.  I didn't miss anything obvious as that was the conclusion I came to after digging.  So I actually have added a qa_showscale keyword that lets the user scale my default sizes up and down depending on what works for them.

**Comment by kelle** [comment]
I think that makes excellent sense and is a great solution to the problem.
