### ISSUE TITLE
Calibrator B and V mags switched in header files

### ISSUE THREAD

**Issue by ctheissen** [pyspextool/pyspextool#172]
This might be specific to batch mode, but the driver file has B and V magnitudes listed as one thing, but the header in the reduced file says something else. Not sure if this is a batch-specific thing, if this is feeding into the reductions, or if this is simply a mistype in the header files.

![image (4)](https://github.com/user-attachments/assets/8bfcc5f6-0680-45a5-8ff1-758a4d52b313)
![image (3)](https://github.com/user-attachments/assets/68f37433-eee4-46a9-b7be-efa55248c3cf)

**Comment by aburgasser** [comment]
Has been identified and will be fixed on next pull
