### ISSUE TITLE
Issue with load_image not accessing the correct index in an array

### ISSUE THREAD

**Issue by ctheissen** [pyspextool/pyspextool#184]
I was running into an issue with`load_image` line 394, where

`z = deltas == np.min(np.abs(deltas))`

Is supposed to return an index value for the `deltas` array where it is equal to the minimum absolute value. However, this was returning an empty array. I fixed it using the following code

`z = np.where(np.abs(deltas) == np.min(np.abs(deltas)))[0]`

Not sure if this is something specific to me, but I ran into it when I was trying to do the `extract` function.

**Comment by aburgasser** [comment]
I fixed this
