### ISSUE TITLE
not passing tests - looking for "LULABEL"

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#186]
I just ran a local pytest and the code is failing at test_combine.py because combine is now looking for LULABEL in the headers of (probably earlier reduction) test data

a grep shows it assigns LULABEL in a few places:
(base) adam@onaeao pyspextool % grep "LULABEL" src/pyspextool/*/*.py      
src/pyspextool/extract/extraction.py:    hdr['LULABEL'] = (latex_ulabel, ' LateX y-axis uncertainty label')    
src/pyspextool/io/read_spectra_fits.py:           'lulabel': header['LULABEL'],           
src/pyspextool/telluric/write_spectra.py:    hdr['LULABEL'][0] = latex[2]    

I suspect this means we need to update the test data, which is always confusing given that these are stored elsewhere. Kelle, advice here?

full test output:

===================================================== FAILURES =====================================================
___________________________________________________ test_combine ___________________________________________________

    def test_combine():
    
        #
        # uSpeX SXD
        #
    
        proc_path = "tests/test_data/processed/uspex-SXD/proc"
        qa_path = "tests/test_data/processed/uspex-SXD/qa"
    
        ps.pyspextool_setup("uspex",
            qa_path=qa_path,
            proc_path=proc_path,
            verbose=True,
            qa_show=False,
            qa_write=True,
            qa_extension=".png",
        )
    
>       ps.combine.combine(["spectra", "1-8"], "cspectra1-8", statistic="mean")

tests/test_combine.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/pyspextool/combine/combine.py:161: in combine
    load_spectra(files,
src/pyspextool/combine/load_spectra.py:140: in load_spectra
    first_spectra, info = read_spectra_fits(combine.state['input_files'][0])
src/pyspextool/io/read_spectra_fits.py:121: in read_spectra_fits
    'lulabel': header['LULABEL'],
/opt/miniconda3/lib/python3.12/site-packages/astropy/io/fits/header.py:170: in __getitem__
    card = self._cards[self._cardindex(key)]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / arra...s)}*naps + (i-1)],                    
HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].                           
key = 'LULABEL'

    def _cardindex(self, key):
        """Returns an index into the ._cards list given a valid lookup key."""
        # This used to just set key = (key, 0) and then go on to act as if the
        # user passed in a tuple, but it's much more common to just be given a
        # string as the key, so optimize more for that case
        if isinstance(key, str):
            keyword = key
            n = 0
        elif isinstance(key, numbers.Integral):
            # If < 0, determine the actual index
            if key < 0:
                key += len(self._cards)
            if key < 0 or key >= len(self._cards):
                raise IndexError("Header index out of range.")
            return key
        elif isinstance(key, slice):
            return key
        elif isinstance(key, tuple):
            if (
                len(key) != 2
                or not isinstance(key[0], str)
                or not isinstance(key[1], numbers.Integral)
            ):
                raise ValueError(
                    "Tuple indices must be 2-tuples consisting of a "
                    "keyword string and an integer index."
                )
            keyword, n = key
        else:
            raise ValueError(
                "Header indices must be either a string, a 2-tuple, or an integer."
            )
    
        keyword = Card.normalize_keyword(keyword)
        # Returns the index into _cards for the n-th card with the given
        # keyword (where n is 0-based)
        indices = self._keyword_indices.get(keyword, None)
    
        if keyword and not indices:
            if len(keyword) > KEYWORD_LENGTH or "." in keyword:
                raise KeyError(f"Keyword {keyword!r} not found.")
            else:
                # Maybe it's a RVKC?
                indices = self._rvkc_indices.get(keyword, None)
    
        if not indices:
>           raise KeyError(f"Keyword {keyword!r} not found.")
E           KeyError: "Keyword 'LULABEL' not found."

/opt/miniconda3/lib/python3.12/site-packages/astropy/io/fits/header.py:1725: KeyError
------------------------------------------------ Captured log call -------------------------------------------------
INFO     root:setup_utils.py:151  Verbose set to True
INFO     root:setup_utils.py:159  Instrument set to uspex
INFO     root:setup_utils.py:167  Paths set
INFO     root:setup_utils.py:173  QA settings set
INFO     root:load_spectra.py:109  Combining Spectra
-----------------------

INFO     root:load_spectra.py:110  Loading the spectra.
================================================= warnings summary =================================================
tests/test_make_wavecal.py: 811 warnings
  /Users/adam/python_codes/pyspextool/src/pyspextool/fit/polyfit.py:395: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    x = np.float64(x)

tests/test_make_wavecal.py: 811 warnings
  /Users/adam/python_codes/pyspextool/src/pyspextool/extract/extraction.py:322: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    aperture_positions[k] = poly_1d(wave, trace_coefficients[l])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================= short test summary info ==============================================
FAILED tests/test_combine.py::test_combine - KeyError: "Keyword 'LULABEL' not found."
=================================== 1 failed, 34 passed, 1622 warnings in 10.11s ===================================

**Comment by kelle** [comment]
Yes, you need to update the `test_data` submodule.  Basically, the `test_data` directory is a nested repository. If you cd into the test_data directory and do a `git status`, you'll see it's different than the parent directories.  Once in the test_data directory, do a `git pull`.
