### ISSUE TITLE
bitmask for the spectra file

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#19]
So in Spextool, besides wavelength, flux density, and uncertainty, there is a fourth column.  It is a way to identify which pixels have certain properties.  Currently, I have four "identities".  

1) one or some of the values that went into this pixel were greater than the linearity correction maximum.
2) one or some of the values that went into this pixel were identified as bad by Spextool and replaced using a model of the spatial profile.
3) one or some of the values that went into this pixel were fixed in the xcleanspec routine.
4) optimal extraction failed on this pixel.

To do this, we use a bitset mask. 

The value for 1) is given by 2^0
                       2) is given by 2^1
                       3) is given by 2^2
                       4) is given by 2^3

So if 1) and 3) are true, the value of the pixel is 2^0+2^2 = 5.
If 3) and 4) are true the value is 2^2+2^3 = 12

Any combination of these is a unique number and so you can decompose it and find which conditions are true.

**Comment by kelle** [comment]
My vision for the spectra files are that they will be Multi-extension FITS files with:
- HDU0 - bunch of metadata about source and observation.
- HDU1 - table with wavelength, flux, and uncertainty.

The above is what I am hoping and will work on making a `specutils` standard.

The way I would implement the bitmask info, which is really specific to `pyspextool`,  is with another extension:
- HDU2 - table with wavelength and bitmask

As the data files get passed around, the HDU2 will get passed around too, but if they try to work with the file using "standard" tools, it won't confuse anyone.

**Comment by michaelcushing** [comment]
Seems reasonable.  I will note that images come with bit masks all the time, e.g. WISE, JWST, etc.  When we started Spextool, uncertainties simply did not exist (I was told by a senior scientist at the time "why would you need that?  You can just measure it from the data").  I would like to think Spextool may have had a part in people thinking spectra should have uncertainties arrays (you would never publish a photometric point with an uncertainty!).  Maybe in the long-term we can convince people that bit masks are useful as well (although I agree the non-standard nature of them may be difficult universify).

**Comment by aburgasser** [comment]
this might be a post process - generate HDU2 with bitmask, background, etc. when converting to a specutils-compliant form - for now keep as 4 columns wave, flux, unc, mask
