### ISSUE TITLE
Test prism data

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#2]
https://www.dropbox.com/s/ez6xnv8dkhn0m3p/flat-00021.a.fits?dl=0

https://www.dropbox.com/s/b6l1x9ccbl4ljk1/spc-00011.a.fits?dl=0

They are a multi-extension FITS files so you want the first (zeroth) extension.

**Comment by kelle** [comment]
@aburgasser will work providing a test data set which includes typical scenarios and modes.

**Comment by aburgasser** [comment]
Added data for spex-prism (ca. 2003); has been pushed (49 files; note: did not require DFS)

**Comment by kelle** [comment]
awesome!  Consider adding a `README.md` in that directory with a brief explanation of what the files are.

**Comment by aburgasser** [comment]
TBD: rename "fileinfo.txt" with "README.md"

**Comment by aburgasser** [comment]
donesy done
