### ISSUE TITLE
Command line user interaction

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#20]
I was assuming that the way people would interact with pyspextool on the command line would be something along the lines of:

from pyspextool import * 

and this would then give them access to the modules/functions they require, e.g. make_flat, make_wavecal, etc.  

Is the best way to do that create a directory called "user" or "reductions" or "cl" (for command line), place all the functions/modules users need to interact with in that directory and then have the user call 

from pyspextool.cl import *?

Just looking to get a sense of how we want to do this.

**Comment by kelle** [comment]
First off: When I think of "command line" interaction, I think of tying commands direct from a shell prompt. It sounds like what you're thinking is the Python prompt or more likely, in a Notebook.  (Actually, I think the most common use case and the easiest way to do all the graphics stuff is to focus on a Notebook environment). Running functions on the _Python_ prompt doesn't require anything extra except, as you say, importing the right module.  

And this question makes me think about the other issue which you brought up about instrument/telescope specificity.  Maybe we want to make instrument specific modules. E.g., 
`from pyspextool import reduce_uspex`

And in `reduce_uspex.py`, we set up all the pointers and imports to the correct data and functions.

**Comment by aburgasser** [comment]
yes, this requires just a small separate python code which we can actually set up to work with any instrument as an input. so for example, you can just call something called spex_reduce_batch.py and point it to a driving file or even just the data directory; e.g., 

> python spex_reduce_batch.py /data/spex/20200505/

BTW, I don't think we should be forcing the user to decide which instrument parameters need to be loaded in, this could be determined directly from the data (could still be different functions, but should be invisible to the user)

**Comment by michaelcushing** [comment]
Oh yes, user's will do nothing but select the instrument, and there will always be a default (the upgraded SpeX).
