### ISSUE TITLE
Testing if dictionaries are equal in pytest

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#21]
I need to find a way to compare two dictionaries.  Assert works for single numbers, 

np.testing_assert_array_equal works for arrays.  What do we use for dictionaries?  I found this,

https://stackoverflow.com/questions/47201358/how-can-you-test-that-two-dictionaries-are-equal-with-pytest-in-python

but when I tried it it didn't like me:

self = <unittest.case.TestCase testMethod=runTest>
d1 = {'goodbad': array([[2, 1, 1],
       [1, 1, 1]]), 'kurtosis': 0.2270065079691186, 'mean': 5.38, 'ndat': 5, ...}
d2 = {'goodbad': array([[2, 1, 1],
       [1, 1, 1]]), 'kurtosis': 0.2270065079691186, 'mean': 5.38, 'ndat': 5, ...}
msg = None

    def assertDictEqual(self, d1, d2, msg=None):
        self.assertIsInstance(d1, dict, 'First argument is not a dictionary')
        self.assertIsInstance(d2, dict, 'Second argument is not a dictionary')
    
>       if d1 != d2:
E       ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

maybe because there is a numpy array in the result, and it cannot simply do asserts between the values?  So maybe I just have to go entry by entry?

**Comment by aburgasser** [comment]
no longer an issue, found a way around it
