### ISSUE TITLE
where do instrument files go?

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#26]
Question is where instrument files go:
issues: large memory hog, not all instruments may be needed, github large file service issue
options:
(1) set up download site (dropbox, amazon) to download instrument files
(2) user installs into correct folder in code path (may cause problems on update)
(3) user installs into separate folder and must include this folder in program variable (e.g., pyspextool.EXTERNAL_INSTRUMENT_FILES = '/Users/adam/data/pyspextool_instruments/'
(4) code automatically downloads instrument files as needed into correct folded in code path if missing
(5) others?

**Comment by kelle** [comment]
We could also host the file on Amazon Web Services and point to a URL. I will ask around about how to cache this file once it's downloaded once.

**Comment by kelle** [comment]
I think astropy has the answer: https://docs.astropy.org/en/stable/utils/data.html

**Comment by aburgasser** [comment]
solved!
