### ISSUE TITLE
minor changes based on test reductions

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#41]
These are mostly for consistency:

- [x]  for make_flat: add qaplot=False to separate plot to screen from plot to file
- [x] for make_wavecal: add qafile=True keyword that will produce all qa files by default, and qaplot=False keyword that will produce all qa files by default; 
- [ ] there is a warning in make_wavecal when writing fits file "card too long, truncated"
- [ ] trace_apertures - currently no option to set trace to aperture position? (important for faint sources)
- [x] no "verbose" for extract.define_aperture_parameters (but maybe not necessary
- [x] may want to hard code (?) constraint that prism mode with slit > 0.3 should always use default solution

**Comment by michaelcushing** [comment]
Just quick for a few of them.


Was hoping to find a slick way around the 0.3 problem, but yeah, probably going to have to hardwire for a bit.  One thing longer term is how do we allow for "drift" in the prism solution.  I am assuming in this code that if I compute it once, it works for all data ever taken.  Clearly incorrect.  I have been considering have the make_wavecal function also spit out a calfile that could be used in place of the default one.  

"card too long", yeah no clue about that. @kelle 

"Trace apertures".  Not in that one, but in the locate_aperture_positions one.  Take a look at the 'fix' method.

Will of course look at the others.

**Comment by kelle** [comment]
@michaelcushing, are all of these still active?  I've changed the list into a check list. If they are longer term todos, they should be broken up into individual issues.

**Comment by michaelcushing** [comment]
I can deal with these soon ish so let's just leave them for now to avoid cluttering.

**Comment by kelle** [comment]
I think these have all been addressed. Can re-open if necessary.
