### ISSUE TITLE
Jupyter Notebook Tutorial for Old SpeX SXD Data

### ISSUE THREAD

**Issue by chihchunhsu** [pyspextool/pyspextool#43]
[Old Spex SXD Extraction Tutorial.ipynb.zip](https://github.com/pyspextool/pyspextool/files/10905030/Old.Spex.SXD.Extraction.Tutorial.ipynb.zip)

Attaching the tutorial for reducing old SpeX SXD data (basically converting what Mike has made in the script) here.

**Comment by aburgasser** [comment]
corrected using the pull infrastructure
