### ISSUE TITLE
adding qafile/qaplot for extraction

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#46]
with the plot_spectra function in place, I recommend we have QA plots for extraction (and eventually combine and flux cal). Will assign myself to this

**Comment by michaelcushing** [comment]
Yeah I think so.  I have QA plots for the combine module (just haven't pushed it yet) and will do the one for telluric when it happens.

**Comment by kelle** [comment]
It's not done until it's pushed!

**Comment by aburgasser** [comment]
just waiting on telluric, but I will close since the intention has been met and they are present in other modules
