### ISSUE TITLE
spectral data structure?

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#47]
We discussed this early on, but I'm wondering if we want to handle the 1D spectra (and multi-order spectrum) as spectrum objects, possibly instances of specutils Spectrum class. 

Why do this? current all spectra are manipulated directly from files (e.g., plot_spectra reads from file, rather than input spectral information), which results in some redundancy (e.g., two read calls if I want to plot spectrum and include information from spectrum header). spectrum object can contain all necessary axes/info and routines for plotting, combining, masking etc.  

Not 100% we want to go fully with specutils since it's not finalized though (they change something => breaks us). 

Up for discussion

**Comment by michaelcushing** [comment]
How does such a thing get stored to disk?

**Comment by kelle** [comment]
Please upload some output spectra to the `test_data/` directory.

Kelle will explore interoperability options with `Spectral1D` class and `specutils`

**Comment by kelle** [comment]
function which writes out spectra is here: https://github.com/pyspextool/pyspextool/blob/main/src/pyspextool/io/write_apertures_fits.py

array contains wavelength, flux, uncertainty, and binary bitmask.

**Comment by kelle** [comment]
To be Pythonic, we probably should have made a spectral class in the first place.

We could (eventually) migrate to using the Spectrum1D class, BUT as far as I can tell, Spectrum1D currently only supports boolean masks. So right now, I don't think we can use it. I just posted in Astropy Slack asking about non-boolean masks.

**Comment by kelle** [comment]
> You can use non-boolean masks in `specutils`. `False` or `0` means the data in that location is good, anything else means it's bad/masked.

I think this means we can use Spectrum1D!
