### ISSUE TITLE
Using Logger instead of Verbose

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#50]
https://docs.python.org/3/library/logging.html

Something to consider for version 2. Replace `verbose` switch with Logger functionality.

**Comment by kelle** [comment]
This is started in #103 in `setup_utils`

**Comment by kelle** [comment]
I'm mapping `verbose = True` onto `DEBUG` and `verbose = False` onto `INFO`.  

How quiet do we want `verbose=false` to be? Maybe `verbose = False` should be `WARNING`?

**Comment by kelle** [comment]
In #123, Adam changed it to:
Verbose = true : info
Verbose = false: warning

This seems reasonable to me.

**Comment by kelle** [comment]
Still need to setup a custom `pyspextool` config and figure out how to log to a file and/or to the screen. Relevant help pages:
- https://rollbar.com/blog/logging-in-python/

**Comment by michaelcushing** [comment]
Using logging now in all new code, and updating as I go back through things.
