### ISSUE TITLE
Installation issues/definition?

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#52]
I had issues installing the current (5/18) version of the code, as it wasn't be recognized by the PYTHONPATH variable. I did a setuptools style installation using 'python3 pip -m install .'**, and that got me running, but now package is in a different part of computer and relative links no longer work (specifically data and test_data folders were not carried over).  So how things are installed is resulting in different relative paths and thus things are breaking when those paths are coded in.

**NOTE: this should be python3 -m pip install -e .

So issues:
- we need to decide a set installation method, and make sure everything works with that (including directory structure)
- do we require/recommend separate conda environments? [what is instruction here?]

**Comment by kelle** [comment]
I am working on this!

**Comment by kelle** [comment]
This was taken care of in #56
