### ISSUE TITLE
internal paths are problematic

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#53]
some of the internal paths to e.g., data, instrument_data are problematic as they go to different folder levels; may fail for different installations.

**Comment by aburgasser** [comment]
e.g. extract/load_image.py ln 331:

            # First we have to get the possible file names

            fullpath = glob.glob(os.path.join(setup.state['package_path'], '..',
                                              '..', 'data', 'atran*.fits'))

[this might be the main one]

**Comment by michaelcushing** [comment]
It may be above this level as I am pretty sure that setup.state['package_path'] is a full directory path and not a relative path. It may be that the way I have coded it that it doesn't always do what I think it does.  It gets set in setup_utils.py if you want to add some print statements to see what that is doing.

**Comment by kelle** [comment]
There's a way to deal with this using setuptools. It described here, but I need to spend some time with it. https://setuptools.pypa.io/en/latest/userguide/datafiles.html#accessing-data-files-at-runtime

**Comment by kelle** [comment]
In PR #54 , I have moved the `data/` directory into the package and now those two extra `..` should no longer be necessary. Once it's merged, it should just be:
```fullpath = glob.glob(os.path.join(setup.state['package_path'], 'data', 'atran*.fits'))```

**Comment by kelle** [comment]
@aburgasser , `data/` has now been moved. Could you pull and see if it works for you now?  If so, I think this issue can be closed.

**Comment by kelle** [comment]
I'm closing this. If the problem persists, please repopen.

**Comment by kelle** [comment]
Another fix was made in `load_image` in a8c7191ebddacb6beec0920cacd4c5ea6f0a16a6
