### ISSUE TITLE
Update package requirements/dependencies

### ISSUE THREAD

**Issue by kelle** [pyspextool/pyspextool#57]
While working on #52 and thinking about our installation method, I also wanted to make sure we understood our package dependencies. I found a script to help out with this and it's telling me that we don't actually use `scipy`.  @michaelcushing , does that ring true to you? Are you importing scipy anywhere?

**Comment by kelle** [comment]
Yeah, that's what I thought. The tool I was using clearly isn't doing what I thought it was doing. Thanks.

**Comment by michaelcushing** [comment]
Those are only loaded if those functions are called though.  Could it be that your tool is only looking at the __init__.py files?

**Comment by kelle** [comment]
Meh, not sure.  Don't care too much. If we're missing a package in one of these files, something will break soon.

New question: Does anyone know our minimum Python requirement? I think we discussed this at some point in the past but I don't remember the answer. I'm using 3.9 and am tempted to make that our minimum.

**Comment by michaelcushing** [comment]
I am at 3.9.12 so I am fine with that.  I thought we decided that in the past but I have no idea where it would have been written down (what file in the package I mean).
