### ISSUE TITLE
plot_spectra is failing for combined SXD data

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#59]
this seems to be an issue in the get_ranges() function, and only applies to combined spectra (individual SXD spectra are fine) and doesn't affect combined prism spectra

```
from pyspextool.plot.plot_spectra import plot_spectra
file = 'combspec1-8.fits'
ax = plot_spectra(proc_path+file,colors='k',y="flux and uncertainty",order_numbers=False)
```

results in following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/jh/fr3p41p17r1g6v0t6k0c2xy00000gq/T/ipykernel_6673/915272899.py in <module>
      4 
      5 file = 'combspec1-8.fits'
----> 6 ax = plot_spectra(proc_path+file,colors='k',y="flux and uncertainty",order_numbers=False)

~/python_codes/pyspextool/src/pyspextool/plot/plot_spectra.py in plot_spectra(file, plot_type, plot_size, y, aperture, xlabel, ylabel, title, colors, line_width, yrange_buffer, order_numbers, file_info, display)
    134     #
    135 
--> 136     wranges, franges, uranges, furanges, sranges = get_ranges(spectra,
    137                                                       info['norders'],
    138                                                       info['napertures'],

~/python_codes/pyspextool/src/pyspextool/plot/plot_spectra.py in get_ranges(spectra, norders, napertures, aperture, fraction)
    363 
    364         unc = spectra[i * napertures + aperture, 2, :]
--> 365         sg_unc = robust_savgol(x_values, unc, 11)['fit']
    366 
    367         unc_ranges[i, :] = get_spec_range(sg_unc, frac=fraction)

~/python_codes/pyspextool/src/pyspextool/fit/robust_savgol.py in robust_savgol(x, y, window_length, polyorder, thresh, eps, goodbad)
    100             oldstddev = stddev
    101 
--> 102             smthyy = scipy.signal.savgol_filter(yy[good], window_length,
    103                                                 polyorder)
    104             residual = yy[good] - smthyy

~/opt/anaconda3/lib/python3.9/site-packages/scipy/signal/_savitzky_golay.py in savgol_filter(x, window_length, polyorder, deriv, delta, axis, mode, cval)
    343     if mode == "interp":
    344         if window_length > x.shape[axis]:
--> 345             raise ValueError("If mode is 'interp', window_length must be less "
    346                              "than or equal to the size of x.")
    347 

ValueError: If mode is 'interp', window_length must be less than or equal to the size of x.

**Comment by michaelcushing** [comment]
Not sure what it going on with this.  But I have made major changes to this code since the last push so let's see what happens when I do the next push.

**Comment by aburgasser** [comment]
still broken

**Comment by michaelcushing** [comment]
Can you send me that file?

**Comment by aburgasser** [comment]
github won't let me upload the file but its here: https://drive.google.com/drive/folders/1Zw19OSodzVLsZlihHg5p_FdMcSiwdoPm?usp=sharing (also in test_data folder)

**Comment by michaelcushing** [comment]
Awesome.  Can you also stick the image that is failing to display in plot_image?

**Comment by michaelcushing** [comment]
Hi Adam.  Can you stick the individual files that went into creating combspec636-645.fits?  This one has inf instead of NaNs in the data and so not sure why that is happening (I think that may be why it is breaking on the comb files).

**Comment by aburgasser** [comment]
hmm, if plot_image is failing, I don't have an image to show you. Not sure what you want here

**Comment by michaelcushing** [comment]
Sorry.  Should have stayed in the right thread.  I mean the fits image that was failing in plot_image (which is a different thread) which you just did send me in the other thread.  Working on this bug at the moment - turns out it is nothing to do with plot_spectra but rather the combine_spectra and specifically the mean_data_stack routine.

**Comment by michaelcushing** [comment]
For the record, I modified the math.mean_data_stack and math.median_data_stack to properly handle all-NaN columns of data.
