### ISSUE TITLE
combine_spectra() scale range - string?

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#60]
combine_spectra() currently takes a scale_range argument that is a string like '1.1-1.3'; however, it can't handle more complex wavelengths like '1.1-1.3, 1.5-1.8, 2.0-2.3' (e.g., like files). So I suggest either (1) it makes more sense to make this a 2-element array or (2) allow more complex windowing like second example, where string format then makes sense

**Comment by michaelcushing** [comment]
Will do #1.  Can't do #2 as the scaling must occur over a single order.

**Comment by michaelcushing** [comment]
Updated on the latest push.
