### ISSUE TITLE
plot_image failing for some flat images?

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#65]
While testing batch mode, ran into a problem when saving normalized flat field file to file (qa_file = True) - maybe a normalization issue? the raw file saved fine

Normalizing the median image...
Normalizing the flat...
100% |**********************************************************************|
---------------------------------------------------------------------------

-----------------
START HERE
-----------------

~/python_codes/pyspextool/src/pyspextool/extract/make_flat.py in make_flat(files, output_name, extension, normalize, overwrite, qa_plot, qa_plotsize, qa_file, verbose)
    283                        'extension': setup.state['qa_extension']}
    284 
--> 285         plot_image(nimg, orders_plotinfo=orders_plotinfo, file_info=qa_fileinfo)
    286 
    287     #

~/python_codes/pyspextool/src/pyspextool/plot/plot_image.py in plot_image(image, mask, orders_plotinfo, trace_plotinfo, locateorders_plotinfo, file_info, plot_size, plot_number)
    151                trace_plotinfo=trace_plotinfo)
    152 
--> 153         pl.savefig(os.path.join(file_info['filepath'], file_info['filename'] + \
    154                                 file_info['extension']))
    155         pl.close()

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py in savefig(*args, **kwargs)
   1021 def savefig(*args, **kwargs):
   1022     fig = gcf()
-> 1023     res = fig.savefig(*args, **kwargs)
   1024     fig.canvas.draw_idle()  # Need this if 'transparent=True', to reset colors.
   1025     return res

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/figure.py in savefig(self, fname, transparent, **kwargs)
   3341                         ax.patch._cm_set(facecolor='none', edgecolor='none'))
   3342 
-> 3343             self.canvas.print_figure(fname, **kwargs)
   3344 
   3345     def ginput(self, n=1, timeout=30, show_clicks=True,

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2364                 # force the figure dpi to 72), so we need to set it again here.
   2365                 with cbook._setattr_cm(self.figure, dpi=dpi):
-> 2366                     result = print_method(
   2367                         filename,
   2368                         facecolor=facecolor,

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/backend_bases.py in <lambda>(*args, **kwargs)
   2230                 "bbox_inches_restore"}
   2231             skip = optional_kws - {*inspect.signature(meth).parameters}
-> 2232             print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
   2233                 *args, **{k: v for k, v in kwargs.items() if k not in skip}))
   2234         else:  # Let third-parties do as they see fit.

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/backends/backend_pdf.py in print_pdf(self, filename, bbox_inches_restore, metadata)
   2813                 RendererPdf(file, dpi, height, width),
   2814                 bbox_inches_restore=bbox_inches_restore)
-> 2815             self.figure.draw(renderer)
   2816             renderer.finalize()
   2817             if not isinstance(filename, PdfPages):

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     93     @wraps(draw)
     94     def draw_wrapper(artist, renderer, *args, **kwargs):
---> 95         result = draw(artist, renderer, *args, **kwargs)
     96         if renderer._rasterizing:
     97             renderer.stop_rasterizing()

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer)
     70                 renderer.start_filter()
     71 
---> 72             return draw(artist, renderer)
     73         finally:
     74             if artist.get_agg_filter() is not None:

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/figure.py in draw(self, renderer)
   3138 
   3139             self.patch.draw(renderer)
-> 3140             mimage._draw_list_compositing_images(
   3141                 renderer, self, artists, self.suppressComposite)
   3142 

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer)
     70                 renderer.start_filter()
     71 
---> 72             return draw(artist, renderer)
     73         finally:
     74             if artist.get_agg_filter() is not None:

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py in draw(self, renderer)
   3062             _draw_rasterized(self.figure, artists_rasterized, renderer)
   3063 
-> 3064         mimage._draw_list_compositing_images(
   3065             renderer, self, artists, self.figure.suppressComposite)
   3066 

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    153                 image_group.append(a)
    154             else:
--> 155                 flush_images()
    156                 a.draw(renderer)
    157         flush_images()

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/image.py in flush_images()
    137         def flush_images():
    138             if len(image_group) == 1:
--> 139                 image_group[0].draw(renderer)
    140             elif len(image_group) > 1:
    141                 data, l, b = composite_images(image_group, renderer, mag)

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer)
     70                 renderer.start_filter()
     71 
---> 72             return draw(artist, renderer)
     73         finally:
     74             if artist.get_agg_filter() is not None:

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/image.py in draw(self, renderer, *args, **kwargs)
    639                 renderer.draw_image(gc, l, b, im, trans)
    640         else:
--> 641             im, l, b, trans = self.make_image(
    642                 renderer, renderer.get_image_magnification())
    643             if im is not None:

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/image.py in make_image(self, renderer, magnification, unsampled)
    947         clip = ((self.get_clip_box() or self.axes.bbox) if self.get_clip_on()
    948                 else self.figure.bbox)
--> 949         return self._make_image(self._A, bbox, transformed_bbox, clip,
    950                                 magnification, unsampled=unsampled)
    951 

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/image.py in _make_image(self, A, in_bbox, out_bbox, clip_bbox, magnification, unsampled, round_to_pixel_border)
    543                 with self.norm.callbacks.blocked(), \
    544                      cbook._setattr_cm(self.norm, vmin=s_vmin, vmax=s_vmax):
--> 545                     output = self.norm(resampled_masked)
    546             else:
    547                 if A.ndim == 2:  # _interpolation_stage == 'rgba'

~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/colors.py in __call__(self, value, clip)
   1344             result.fill(0)  # Or should it be all masked?  Or 0.5?
   1345         elif vmin > vmax:
-> 1346             raise ValueError("minvalue must be less than or equal to maxvalue")
   1347         else:
   1348             if clip:

ValueError: minvalue must be less than or equal to maxvalue

**Comment by michaelcushing** [comment]
Can you send me the flat image that it created so that I can figure this out?

**Comment by kelle** [comment]
Please try uploading the image here. It might be too big but let's try it!

**Comment by aburgasser** [comment]
attaching as zip file
[flat34-39.fits.zip](https://github.com/pyspextool/pyspextool/files/11926962/flat34-39.fits.zip)

**Comment by michaelcushing** [comment]
I have fixed this issue so things will run, but the "bad" images won't display well.  I am going to open a new issue that we can deal with later.
