### ISSUE TITLE
test_data reductions

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#70]
@aburgasser 

I noticed that the reductions for the test_data got placed in the same data as the raw directory, e.g. everything is in test_data/uspex-SXD.  We can't do that as the code cannot handle when there is more than 1 file with the same index number, e.g. spc-00001.a.fits and spectra00001.fits.  Perhaps we set up a raw/, cal/, proc/, qa/ structure within each directory?

**Comment by aburgasser** [comment]
Yup, I will fix this, we also saw a problem today that the test data didn't port over on install since it's not in src, so I'll do a reshuffle while I'm at it!

**Comment by michaelcushing** [comment]
Sounds good.  Just looping in @kelle because I feel like we did this move once before because something wasn't syncing properly.

**Comment by aburgasser** [comment]
yes, we had to do it with the instrument_data, just moved it into src. it's actually not that big of a deal because the test_data aren't required for the code to run

**Comment by kelle** [comment]
I think this is taken care of. If not, please re-open.
