### ISSUE TITLE
moving off LFS

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#71]
move test_data of repository and move to zenodo for external download, instructions to link up

**Comment by kelle** [comment]
After posting to three different Slack channels, the best idea I've gotten is to move the data to Cloudflare: 

A possibility would be to investigate cloud storage. E.g. hosting the data in a public Cloudflare R2 bucket (https://www.cloudflare.com/products/r2/) should be pretty affordable, and it can just be downloaded as needed. It's much cheaper than LFS for pricing (1.5 c / GB / month storage, 36 c / million read operations, no bandwidth cost) - the test script would then just download the data as needed.

**Comment by kelle** [comment]
Adam is going to discuss with John Rayner what he prefers from an IRTF perspective.

**Comment by kelle** [comment]
In #112 , I've moved the test_data directory to a dedicated repository. This should minimize the LFS bandwidth. I think this should resolve a lot of the concerns.
