### ISSUE TITLE
File sizes are much bigger than old IDL spextool

### ISSUE THREAD

**Issue by ctheissen** [pyspextool/pyspextool#76]
I have only noticed this for the flat and wavecal files, which are now 100.7 MB and 69.1 MB, respectively. In the IDL version of spextool those file sizes were both 37.8 MB.

@michaelcushing thought it might have to do with integer bitmasks not being integers.

**Comment by michaelcushing** [comment]
Starting to think it may be because they are getting written as sign 64 bit images!  Hopefully will have this figure out in the next few days.
