### ISSUE TITLE
Add astroquery and update dependencies

### ISSUE THREAD

**Issue by michaelcushing** [pyspextool/pyspextool#80]
Please add astroquery to whatever needs to be added to.  I use it to query SIMBAD for information on the standard star.

**Comment by aburgasser** [comment]
also pandas per #77

**Comment by kelle** [comment]
@michaelcushing is going to write a test which uses astroquery. 
@kelle is gonna figure out `requirements.txt` vs `.toml` and update accordingly.

**Comment by kelle** [comment]
The internet told me:
> your .toml files should include the list of abstract dependencies, whereas the requirements.txt file must contain the concrete dependencies with the specific pins for each package version (using == pin).

**Comment by kelle** [comment]
Done in #88 and #91 .
