### ISSUE TITLE
installation instructions wrong?

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#83]
The first pip install command listed in the README throws an error:

(base) adam@onaeao python_codes % pip install -e pyspextool@git+https://github.com/pyspextool/pyspextool.git
ERROR: pyspextool@git+https://github.com/pyspextool/pyspextool.git is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by aburgasser** [comment]
similarly, if I leave out the pyspextool@:

(base) adam@onaeao python_codes % pip install -e git+https://github.com/pyspextool/pyspextool.git                       

ERROR: Could not detect requirement name for 'git+https://github.com/pyspextool/pyspextool.git', please specify one with #egg=your_package_name

**Comment by michaelcushing** [comment]
I assume this is an @kelle question as I don't believe that I have messed with these sorts of things before.

**Comment by kelle** [comment]
For users, it's probably the "-e" that's the problem. Try 
```
pip install pyspextool@git+https://github.com/pyspextool/pyspextool.git
```

**Comment by kelle** [comment]
I believe getting rid of the `-e` fixed this problem and Adam updated the README.
