### ISSUE TITLE
error in make_flat - looking for a missing header key

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#84]
Having a critical fail in make_flat.py where it is looking for a SLIT key in an average_header; found while running the batch mode on the test_data in https://drive.google.com/drive/folders/1NwpIEsyuUxBCv9L8YVGkXvF6oJg_7Hnl?usp=sharing 

Traceback (most recent call last):
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 188, in <module>
    app = runBatch()
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 158, in __init__
    batch_reduce(par,verbose=args['verbose'])
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/batch/batch.py", line 1145, in batch_reduce
    ps.extract.make_flat([parameters['FLAT_FILE_PREFIX'],fstr],'flat{}'.format(cs),qa_plot=parameters['QA_PLOT'],qa_file=parameters['QA_FILE'],verbose=parameters['VERBOSE'])
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/extract/make_flat.py", line 313, in make_flat
    slitw_arc = float(average_header['SLIT'][0][0:3])
KeyError: 'SLIT'

offending line:
313    slitw_arc = float(average_header['SLIT'][0][0:3])

contents of average_header (no "SLIT"):

AVE_AM:
- '1.005'
- Average airmass
AVE_DATE:
- '2003-05-21'
- Average observation date in UTC
AVE_HA:
- '+00:15:38.87'
- Average hour angle (hours)
AVE_MJD:
- '52780.26467880845'
- Average modified Julian date
AVE_TIME:
- '+06:21:08.25'
- Average observation time in UTC
BEAM:
- A
- Object(A) or sky(B)
CYCLES:
- 5
- Number of cycles
DEC:
- '+15:46:35.7'
- ' Declination'
DIVISOR:
- 24
- Normalization value
END_AM:
- 1.005
- End airmass
END_DATE:
- '2003-05-21'
- End observation date in UTC
END_HA:
- '+00:16:30.38'
- End hour angle (hours)
END_MJD:
- !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    rdEffYjF6UA=
- End airmass
END_TIME:
- '06:21:59.670279'
- End observation time in UTC
FILENAME:
- flat0015.a.fits
- ' Filename'
GFLT:
- K
- menu=4,pos=192000
IMGITIME:
- 12.600000000000001
- ' Image integration time, NCOADDSxITIME (sec)'
INSTR:
- SpeX
- ' Instrument'
ITIME:
- 1.05
- ' Integration time (sec)'
MODE:
- LowRes15
- ' Instrument Mode'
NCOADDS:
- 12
- ' Number of COADDS'
NDR:
- 2
- Number of Non-Destructive Reads
OBJECT:
- Inc Lamp
- ''
OBSERVER:
- burgasser
- ''
ORIGIN:
- Institute for Astronomy
- ''
PA:
- 0.0
- ' Position Angle E of N (deg)'
RA:
- '11:37:57.46'
- ' Right Ascension'
SRT_AM:
- 1.004
- Start airmass
SRT_DATE:
- '2003-05-21'
- Start observations date in UTC
SRT_HA:
- '+00:14:47.20'
- Start hour angle (hours)
SRT_MJD:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    6jtec4jF6UA=
- Start modified Julian date
SRT_TIME:
- '06:20:16.772948'
- Start observations time in UTC
TABLE_MS:
- 512.452
- msec to clock out array
TELESCOP:
- NASA IRTF
- ''
TOTITIME:
- 63.00000000000001
- Total integration time (sec)
USERCOM:
- Flat
- ' User comment'

**Comment by michaelcushing** [comment]
Reproduced.  Looking into it.

**Comment by michaelcushing** [comment]
Fixed and pushed.  For posterity, in my modification of the FITS header handling, I dropped a keyword from the list "grab these keywords".
