### ISSUE TITLE
better Installation instructions

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#88]
Task is to write clear installation instructions that can be followed by novices with various computer configurations.

@kelle  & @ctheissen  - conda instructions of linux and MaxOS (with modifications for different chip types)
@adam - windows installation

For all, I'd recommend first installation of Anaconda Navigator or mini-anaconda (wls, ubuntu as back-up options?)

Windows notes:
- run all the commands from Anaconda terminal (CMD.exe in Anaconda Navigator) <-- this is critical
- [conda instructions]

Also necessary - setting environment variable to PYTHONPATH:

- For MacOS or Linux: add the following line to your ~/.bashrc (MacOS 11.X and earlier) or ~/.zshrc (MacOS 12.X and later):
-- export PYTHONPATH=/Users/adam/python_codes/pyspextool:$PYTHONPATH

Note: replace "/Users/adam/python_codes/pyspextool" with the path to your pyspextool directory.
 
- For Windows: see https://www.java.com/en/download/help/path.html for how to set environmental variables; either create or add to PYTHONPATH the pyspextool folder

Questions on conda environment
- how do users set this in jupyter notebook? if calling from Anaconda Navigator?
- how do we signal to users that they need to upgrade/install packages?

Some typical fail modalities
- installation script fails because user doesn't have write access to top level directories - sudo sometimes worked, but also resulted in installation for sudo user instead of current user; Anaconda installation fixed most of these issues
- wrong syntax for environmental variable
- missing or outdated packages - conda environment may fix this
- no pip or conda commands not recognized - anaconda installation fixed most of these issues

**Comment by kelle** [comment]
- Using conda should negate the need to do anything with environment variables. 
- Yes, conda will also address the missing/outdated packages
