### ISSUE TITLE
Need a more flexible environment.yml file

### ISSUE THREAD

**Issue by chihchunhsu** [pyspextool/pyspextool#93]
I did the most recent pull but failed to find the environment. Can we have a more flexible environment (e.g. compare with everyone's package version and determined the necessary ones? 

`conda env create -f environment.yml`

> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound:
> 
> xorg-libxdmcp==1.1.3=h27ca646_0
> keyring==24.2.0=py311h267d04e_0
> ncurses==6.4=h7ea286d_0
> libjpeg-turbo==2.1.5.1=h1a8c8d9_0
> libcblas==3.9.0=17_osxarm64_openblas
> libdeflate==1.18=h1a8c8d9_0
> libbrotlienc==1.0.9=h1a8c8d9_9
> pyyaml==6.0=py311he2be06e_5
> astropy==5.3.1=py311hb49d859_0
> lerc==4.0.0=h9a09cb3_0
> liblapack==3.9.0=17_osxarm64_openblas
> libopenblas==0.3.23=openmp_hc731615_0
> openssl==3.1.1=h53f4e23_1
> libffi==3.4.2=h3422bc3_5
> xorg-libxau==1.0.11=hb547adb_0
> libgfortran==5.0.0=12_3_0_hd922786_0
> readline==8.2=h92ec313_1
> libpng==1.6.39=h76d750c_0
> libzlib==1.2.13=h53f4e23_5
> pthread-stubs==0.4=h27ca646_1001
> freetype==2.12.1=hd633e50_1
> libblas==3.9.0=17_osxarm64_openblas
> tornado==6.3.2=py311heffc1b2_0
> yaml==0.2.5=h3422bc3_2
> matplotlib-base==3.7.2=py311h3bc9839_0
> tk==8.6.12=he1e0b03_0
> pandas==2.0.3=py311h9e438b8_1
> openjpeg==2.5.0=hbc2ba62_2
> libcxx==16.0.6=h4653b0c_0
> matplotlib==3.7.2=py311ha1ab1f8_0
> pyerfa==2.0.0.3=py311h4add359_0
> pillow==10.0.0=py311h095fde6_0
> lcms2==2.15=hd835a16_1
> libwebp-base==1.3.1=hb547adb_0
> numpy==1.25.1=py311hb8f3215_0
> kiwisolver==1.4.4=py311hd6ee22a_1
> libxcb==1.15=hf346824_0
> scipy==1.11.1=py311h93d07a4_0
> llvm-openmp==16.0.6=h1c12783_0
> bzip2==1.0.8=h3422bc3_4
> libexpat==2.5.0=hb7217d7_1
> python==3.11.4=h47c9636_0_cpython
> libgfortran5==12.3.0=ha3a6a3e_0
> brotli-python==1.0.9=py311ha397e9f_9
> libtiff==4.5.1=h23a1a89_0
> libbrotlidec==1.0.9=h1a8c8d9_9
> libsqlite==3.42.0=hb31c410_0
> ca-certificates==2023.5.7=hf0a4a13_0
> xz==5.2.6=h57fd34a_0
> contourpy==1.1.0=py311he4fd1f5_0
> fonttools==4.41.1=py311heffc1b2_0
> brotli-bin==1.0.9=h1a8c8d9_9
> libbrotlicommon==1.0.9=h1a8c8d9_9
> brotli==1.0.9=h1a8c8d9_9
> zstd==1.5.2=h4f39d0f_7

**Comment by kelle** [comment]
I learned from the sciware forum:
-  use the top-level packages, and only put version restrictions if I know there's an issue (e.g., I updated matplotlib to use a newer feature).
- `grep -h 'import' dir/*py | sort | uniq` will generate a list of all your unique import statements, which is an easier place to start then going through all your .py files manually

**Comment by kelle** [comment]
@chihchunhsu , Why don't you take a stab at generating us a new, simpler `environment.yml` file.

**Comment by kelle** [comment]
Progress was made in #105 but I think we may still need add git-lfs to it.
