### ISSUE TITLE
overwrite flags in several functions throw errors when it would be better to just skip

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#94]
I just noticed the overwrite keyword in make_flat, make_wavecal, combine_spectra, and telluric_correction (but NOT in extract_apertures or do_all_steps). I assumed this would just check if the file was there and if so just return, but instead it throws an error that stops the code, which means to the only real option is to overwrite or fail. I would suggest checking for the presence of the output file and overwrite flag first and then returning (maybe with warning message) rather than raising an OSError. Would also be good to add these to extract_apertures or do_all_steps

**Comment by michaelcushing** [comment]
Oh, that wasn't intentional.  I will get them all to True.

**Comment by aburgasser** [comment]
it doesn't matter if it's True or False as default, it would be good for it to not crash on OSError for either option

**Comment by michaelcushing** [comment]
Ah.  I missed the point.  Can you copy the error here so I can see it as I have never had that problem.

**Comment by aburgasser** [comment]
sorry, it breaks in the other codes; the main ask is that if overwrite = False and the file exists, the relevant code(s) simple skip that reduction step, rather than throw an OSError

**Comment by michaelcushing** [comment]
Will fix when we figure out the answer to #129.

**Comment by michaelcushing** [comment]
We simply removed the ability for the user to choose whether to overwrite things.
