### ISSUE TITLE
minor bug at end of telluric correction

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#96]
got the following error:

Traceback (most recent call last):
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 227, in <module>
    app = runBatch()
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 197, in __init__
    batch.batch_reduce(par,verbose=(not args['quiet']))
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/batch/batch.py", line 1472, in batch_reduce
    ps.telluric.telluric_correction('{}{}.fits'.format(spar['COMBINED_FILE_PREFIX'],spar['TARGET_FILES']),spar['STD_NAME'],
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/telluric/telluric_correction.py", line 349, in telluric_correction
    history = split_text(old_history, length=65)            
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/utils/split_text.py", line 52, in split_text
    pos = ntext.rfind(' ', 0, length-1+i)
AttributeError: 'list' object has no attribute 'rfind'

this appears to be in the "cleanup" stage the code is extracting the old history from the object file header:

old_history = object_hdrinfo['HISTORY']

but for this particular case old_history is a list of strings, not text:

['Spextool FITS files contain an array of size', '[nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains', 'the data ... 1.1872539659152526.']

probably because there are multiple HISTORY lines? 

minor nuisance, but causes the code to crash without completing the telluric step. Probably split_text needs to check if it's passed a string or list of strings and flatten the latter.

**Comment by michaelcushing** [comment]
Can you send me the individual files where this broke?  When I downloaded it was just the combspec69-234.fits file.

**Comment by michaelcushing** [comment]
@aburgasser Just a poke on this.  If you can put the entire data (all the individual spectra for both std and obj since the problem may be with combine) I can then take a look.

**Comment by aburgasser** [comment]
the individual combspec files are here: https://drive.google.com/drive/folders/1BxZ8KIvOfBzsL8d7dq9xqWb4NqDuREJv - let me know if/when you need individual spectral files

**Comment by michaelcushing** [comment]
So running this code in the directory with the two files, I was able to telluric correction the data.  So perhaps after we get everything synced, you can try running this again?

ps.pyspextool_setup(raw_path='./', qa_path='./', cal_path='./',
                    proc_path='./', verbose=True, qa_show=False, qa_write=True,
                    qa_extension='.png')

ps.telluric.telluric_correction('combspec69-234.fits', 'HD 213066',
                                'combspec185-190.fits', 'test',
                                fluxdensity_units='Jy')

**Comment by kelle** [comment]
I think this is stale. If not, can re-open.
