### ISSUE TITLE
log.csv file has a space after the + in the coordinates, which breaks it

### ISSUE THREAD

**Issue by ctheissen** [pyspextool/pyspextool#99]
There is an issue in the log file that is created which puts a space after the + in coordinates, e.g., "+ 13:13:13.00". This is breaking the code. It works if I remove the spaces in the log file.

**Comment by aburgasser** [comment]
can you post your log.csv, I'm not reproducing this (but it's probably an easy fix)

**Comment by ctheissen** [comment]
Here is my log file.
[log.csv](https://github.com/pyspextool/pyspextool/files/12194962/log.csv)

**Comment by aburgasser** [comment]
fixed in most recent version - make sure to update (and you might need to rebuild your log.csv)
